import { Patient, PatientsMap } from '../types';

export function formatDate(dateString: string | null): string {
  if (!dateString) return 'N/A';
  const date = new Date(dateString);
  return date.toLocaleString();
}

export function downloadTextFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadJsonFile(data: unknown, filename: string): void {
  const blob = new Blob([JSON.stringify(data, null, 2)], {
    type: 'application/json',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportPatient(patientName: string, patient: Patient): void {
  const patientData = {
    name: patientName,
    age: patient.age,
    sex: patient.sex,
    notes: patient.note,
    recordingDate: patient.recordingDate || null,
    lastModified: patient.lastModified || null,
    hasRecording: !!patient.waveform,
  };

  // Create detailed text report
  const content = `PATIENT MEDICAL REPORT
==========================================
Patient Name: ${patientData.name}
Age: ${patientData.age || 'Not specified'}
Sex: ${patientData.sex || 'Not specified'}
Recording Date: ${formatDate(patientData.recordingDate)}
Last Modified: ${formatDate(patientData.lastModified)}
Has Audio Recording: ${patientData.hasRecording ? 'Yes' : 'No'}

DOCTOR'S NOTES:
==========================================
${patientData.notes || 'No notes recorded.'}

TECHNICAL INFORMATION:
==========================================
Heart sound recording duration: 60 seconds
Analysis segment: 30-40 seconds (filtered 10-100Hz)
Export date: ${formatDate(new Date().toISOString())}
Generated by: Heart Audio Recorder System`;

  // Download text report
  downloadTextFile(content, `${patientName}_Medical_Report.txt`);

  // Also export JSON format backup
  downloadJsonFile(patientData, `${patientName}_Backup_Data.json`);
}

export function exportAllPatients(patients: PatientsMap): void {
  const allPatientsData = {
    exportDate: new Date().toISOString(),
    exportVersion: '1.0',
    totalPatients: Object.keys(patients).length,
    patients: {} as Record<string, {
      age: string;
      sex: string;
      notes: string;
      recordingDate: string | null;
      lastModified: string | null;
      hasRecording: boolean;
    }>,
  };

  // Process each patient data
  for (const name in patients) {
    allPatientsData.patients[name] = {
      age: patients[name].age,
      sex: patients[name].sex,
      notes: patients[name].note,
      recordingDate: patients[name].recordingDate || null,
      lastModified: patients[name].lastModified || null,
      hasRecording: !!patients[name].waveform,
    };
  }

  // Create detailed summary report
  let summaryContent = 'ALL PATIENTS MEDICAL REPORT\n';
  summaryContent += '==========================================\n';
  summaryContent += 'Export Date: ' + formatDate(allPatientsData.exportDate) + '\n';
  summaryContent += 'Total Patients: ' + allPatientsData.totalPatients + '\n';
  summaryContent += 'Generated by: Heart Audio Recorder System\n\n';

  let patientIndex = 1;
  for (const name in allPatientsData.patients) {
    const patient = allPatientsData.patients[name];

    summaryContent += '==========================================\n';
    summaryContent += patientIndex + '. PATIENT: ' + name + '\n';
    summaryContent += '==========================================\n';
    summaryContent += 'Age: ' + (patient.age || 'Not specified') + '\n';
    summaryContent += 'Sex: ' + (patient.sex || 'Not specified') + '\n';
    summaryContent +=
      'Has Audio Recording: ' + (patient.hasRecording ? 'Yes' : 'No') + '\n';
    summaryContent += 'Recording Date: ' + formatDate(patient.recordingDate) + '\n';
    summaryContent += 'Last Modified: ' + formatDate(patient.lastModified) + '\n\n';
    summaryContent += "DOCTOR'S NOTES:\n";
    summaryContent += (patient.notes ? patient.notes : 'No notes recorded.') + '\n\n';

    patientIndex++;
  }

  summaryContent += '==========================================\n';
  summaryContent += 'END OF REPORT\n';
  summaryContent += 'Generated on: ' + formatDate(new Date().toISOString()) + '\n';

  // Download detailed report and JSON backup
  const dateStr = new Date().toISOString().split('T')[0];
  downloadTextFile(summaryContent, 'All_Patients_Medical_Report_' + dateStr + '.txt');
  downloadJsonFile(allPatientsData, 'All_Patients_Backup_' + dateStr + '.json');
}

export function downloadAudioFile(blob: Blob, patientName: string, patient: Patient): void {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const patientInfo = `${patientName}_Age${patient.age || 'Unknown'}_${patient.sex || 'Unknown'}_${timestamp}`;
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${patientInfo}_HeartSound_60s.wav`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

